name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - numpy=1.22.4
  - scipy=1.8.1
  - matplotlib=3.5.2
  - scikit-learn=1.1.1
  - ipywidgets=7.7.0
  - pandas=1.4.2
